version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
    - npm install
    - npm install -g angular-cli
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
    - ng build 
  post_build:
    commands:
    - aws s3 sync ./dist s3://serverless-app-heroes-sl
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
