version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
#  install:
#    commands:
   - npm install
   - npm install -g @angular/cli
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
    - ng build
   # - sudo apt-get update && sudo apt-get install -y ruby ruby-dev && apt-get clean && sudo gem install compass && sudo npm install && sudo npm install grunt-cli && sudo npm install bower && sudo ./node_modules/bower/bin/bower install --allow-root && sudo ./node_modules/grunt-cli/bin/grunt build
  post_build:
    commands:
    - aws s3 sync ./dist s3://serverless-app-heroes-sl
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
